const root=document.documentElement,chapters=[...document.querySelectorAll('.chapter')],prev=document.querySelector('.arrow--prev'),next=document.querySelector('.arrow--next'),progressLabel=document.querySelector('.progress-label'),progressName=document.querySelector('.progress-name'),menu=document.querySelector('.journey-menu'),menuTrigger=document.querySelector('.menu-trigger'),dialog=document.querySelector('.identity-dialog'),smartappsDialog=document.querySelector('.smartapps-dialog');
const names=['Origin','SmartCore EOS','Enterprise takes form','Every operation connected','Intelligence throughout','Built to expand','Complete universe'];let current=0,wheelTotal=0,wheelTimer,locked=false,touchStart=null;
function closeMenu(){menu.classList.remove('is-open');menuTrigger.setAttribute('aria-expanded','false')}
function goTo(index){const target=Math.max(0,Math.min(6,index));if(target===current)return;current=target;root.style.setProperty('--current',current);chapters.forEach((chapter,i)=>{const active=i===current;chapter.classList.toggle('is-current',active);chapter.inert=!active;chapter.setAttribute('aria-hidden',String(!active))});progressLabel.textContent=`${String(current+1).padStart(2,'0')} / 07`;progressName.textContent=names[current];prev.disabled=current===0;next.disabled=current===6;history.replaceState(null,'',`#scene-${current+1}`);closeMenu()}
function step(direction){if(!locked){locked=true;goTo(current+direction);setTimeout(()=>locked=false,850)}}
prev.addEventListener('click',()=>step(-1));next.addEventListener('click',()=>step(1));document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>goTo(Number(button.dataset.go))));menuTrigger.addEventListener('click',()=>{const open=menuTrigger.getAttribute('aria-expanded')!=='true';menuTrigger.setAttribute('aria-expanded',String(open));menu.classList.toggle('is-open',open)});document.querySelectorAll('.identity-trigger,.final-identity').forEach(button=>button.addEventListener('click',()=>dialog.showModal()));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());document.querySelector('.smartapps-trigger').addEventListener('click',()=>smartappsDialog.showModal());document.querySelector('.smartapps-close').addEventListener('click',()=>smartappsDialog.close());
addEventListener('keydown',event=>{if(dialog.open||smartappsDialog.open||registerDialog.open||contactDialog.open)return;if(event.key==='Escape')closeMenu();if(['ArrowRight','PageDown',' '].includes(event.key)){event.preventDefault();step(1)}if(['ArrowLeft','PageUp'].includes(event.key)){event.preventDefault();step(-1)}if(event.key==='Home')goTo(0);if(event.key==='End')goTo(6)});
addEventListener('wheel',event=>{if(dialog.open||smartappsDialog.open||registerDialog.open||contactDialog.open||menu.classList.contains('is-open'))return;event.preventDefault();wheelTotal+=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>wheelTotal=0,180);if(Math.abs(wheelTotal)>42){step(wheelTotal>0?1:-1);wheelTotal=0}},{passive:false});
addEventListener('touchstart',event=>{const t=event.touches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});addEventListener('touchend',event=>{if(!touchStart)return;const t=event.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1);touchStart=null},{passive:true});
const initial=Number((location.hash.match(/scene-(\d)/)||[])[1]||1)-1;if(initial>0){current=-1;goTo(initial)}
const positionObserver=new MutationObserver(()=>{const index=chapters.findIndex(chapter=>chapter.classList.contains('is-current'));root.style.setProperty('--offset',`${index*-100}vw`);root.style.setProperty('--progress',`${((index+1)/7)*100}%`)});chapters.forEach(chapter=>positionObserver.observe(chapter,{attributes:true,attributeFilter:['class']}));root.style.setProperty('--offset',`${current*-100}vw`);root.style.setProperty('--progress',`${((current+1)/7)*100}%`);
const optimizedNames=['01-formation','02-awakening','03-intelligence','04-connection','05-orchestration','06-expansion','07-complete-core'];const warmed=new Set();function warmScene(index){if(index<0||index>6||warmed.has(index))return;warmed.add(index);const mobile=matchMedia('(max-width:760px)').matches;const image=new Image();image.decoding='async';image.src=`assets/optimized/${optimizedNames[index]}-${mobile?'mobile':'desktop'}.webp`}const assetObserver=new MutationObserver(()=>{const index=chapters.findIndex(chapter=>chapter.classList.contains('is-current'));warmScene(index);warmScene(index+1);warmScene(index-1)});chapters.forEach(chapter=>assetObserver.observe(chapter,{attributes:true,attributeFilter:['class']}));progressName.setAttribute('aria-live','polite');warmScene(current);warmScene(current+1);
const welcome=document.querySelector('.welcome'),audio=document.querySelector('#welcome-audio'),soundControl=document.querySelector('.sound-control'),soundLabel=soundControl.querySelector('span'),originTitle=document.querySelector('#title-1');originTitle.tabIndex=-1;function updateSound(playing){soundControl.setAttribute('aria-pressed',String(playing));soundControl.setAttribute('aria-label',playing?'Pause soundtrack':'Play soundtrack');soundLabel.textContent=playing?'Sound on':'Sound off'}function enterExperience(withSound){welcome.classList.add('is-entered');if(withSound){audio.volume=.62;audio.play().then(()=>updateSound(true)).catch(()=>updateSound(false))}else updateSound(false);startAuto();setTimeout(()=>originTitle.focus(),1050)}document.querySelector('.enter-experience').addEventListener('click',()=>enterExperience(true));document.querySelector('.enter-silent').addEventListener('click',()=>enterExperience(false));soundControl.addEventListener('click',()=>{if(audio.paused)audio.play().then(()=>updateSound(true)).catch(()=>updateSound(false));else{audio.pause();updateSound(false)}});audio.addEventListener('pause',()=>updateSound(false));audio.addEventListener('play',()=>updateSound(true));
const autoControl=document.querySelector('.auto-control'),autoLabel=autoControl.querySelector('span');let autoTimer=null,autoPlaying=true;const AUTO_DELAY=6000;function updateAuto(){autoControl.setAttribute('aria-pressed',String(autoPlaying));autoControl.setAttribute('aria-label',autoPlaying?'Pause automatic journey':'Play automatic journey');autoLabel.textContent=autoPlaying?'Auto on':'Auto off';autoControl.classList.remove('is-counting');void autoControl.offsetWidth;if(autoPlaying&&current<6)autoControl.classList.add('is-counting')}function scheduleAuto(){clearTimeout(autoTimer);if(!autoPlaying||current>=6||!welcome.classList.contains('is-entered')){updateAuto();return}autoTimer=setTimeout(()=>{goTo(current+1);scheduleAuto()},AUTO_DELAY);updateAuto()}function startAuto(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){autoPlaying=false;updateAuto();return}autoPlaying=true;scheduleAuto()}autoControl.addEventListener('click',()=>{autoPlaying=!autoPlaying;if(autoPlaying&&current>=6)goTo(0);scheduleAuto();updateAuto()});['wheel','keydown','touchstart','pointerdown'].forEach(type=>addEventListener(type,event=>{if(event.target.closest?.('.auto-control'))return;if(autoPlaying&&welcome.classList.contains('is-entered'))scheduleAuto()},{passive:true,capture:true}));

/* ============ Finishing pass — Netlify Forms integration (SmartApp register interest + contact) ============
   On an authorised Netlify deployment this form POSTs to the Netlify server using an encoded
   body. On a local preview (localhost / 127.0.0.1 / file:) no data is transmitted — a clearly
   labelled development-state is shown instead. Success is never faked, failures are never
   swallowed, and submitted values are retained on failure. See finishing-report.md for the
   owner's remaining Netlify setup steps. */
const registerDialog=document.querySelector('.register-dialog'),contactDialog=document.querySelector('.contact-dialog'),registerTrigger=document.querySelector('.register-trigger'),contactTrigger=document.querySelector('.contact-trigger'),registerForm=document.querySelector('.register-form'),registerPending=document.querySelector('#register-pending'),registerSubmitBtn=document.querySelector('.register-submit__btn');let registerSending=false;
function suspendAuto(){autoPlaying=false;scheduleAuto();updateAuto()}
document.querySelectorAll('.identity-trigger,.final-identity,.smartapps-trigger').forEach(t=>t.addEventListener('click',suspendAuto));
registerTrigger.addEventListener('click',()=>{suspendAuto();registerDialog.showModal();setTimeout(()=>document.getElementById('reg-name').focus(),0)});
contactTrigger.addEventListener('click',()=>{suspendAuto();contactDialog.showModal()});
document.querySelector('.register-close').addEventListener('click',()=>registerDialog.close());
document.querySelector('.contact-close').addEventListener('click',()=>contactDialog.close());
registerDialog.addEventListener('close',()=>{registerSending=false;registerSubmitBtn.disabled=false;registerPending.removeAttribute('aria-busy');registerPending.hidden=true;registerPending.textContent=''});
contactDialog.addEventListener('close',()=>{});
function setFieldError(id,msg){const input=document.getElementById(id),box=document.getElementById(id+'-error');if(msg){input&&input.setAttribute('aria-invalid','true');box&&(box.textContent=msg,box.hidden=false)}else{input&&input.removeAttribute('aria-invalid');box&&(box.textContent='',box.hidden=true)}}
function validateRegister(){let ok=true;const errors=[];const setErr=(id,msg)=>{setFieldError(id,msg);if(msg)errors.push(id)};const field=id=>document.getElementById(id);const name=field('reg-name').value.trim(),org=field('reg-org').value.trim(),email=field('reg-email').value.trim(),size=field('reg-size').value;setErr('reg-name',name?'':'Full name is required.');setErr('reg-org',org?'':'Organisation is required.');if(!email)setErr('reg-email','Work email is required.');else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))setErr('reg-email','Enter a valid work email address.');else setFieldError('reg-email','');setErr('reg-size',size?'':'Please select your organisation size.');const apps=[...document.querySelectorAll('input[name=smartapps]')],appsBox=document.getElementById('reg-apps-error');if(!apps.some(a=>a.checked)){appsBox.textContent='Select at least one SmartApp of interest.';appsBox.hidden=false;errors.push('apps')}else{appsBox.textContent='';appsBox.hidden=true}setErr('reg-consent',field('reg-consent').checked?'':'Please consent to Tonaque using your information to respond to your enquiry.');if(errors.length){const first=['reg-name','reg-org','reg-email','reg-size','apps','reg-consent'].find(id=>errors.includes(id));if(first==='apps'){apps[0].focus()}else{const el=field(first);el&&el.focus()}return false}return true}
function clearFieldErrors(){['reg-name','reg-org','reg-email','reg-size','reg-consent'].forEach(id=>setFieldError(id,''));const box=document.getElementById('reg-apps-error');box.textContent='';box.hidden=true}
function isLocalPreview(){return location.protocol==='file:'||['localhost','127.0.0.1','0.0.0.0','::1','[::1]'].includes(location.hostname)}
function contactFallbacks(){return '<a class="register-fallback" href="mailto:admin@tonaquedigital.co.zw">Email Tonaque</a><a class="register-fallback" href="tel:+263776706614">Call +263 77 670 6614</a><a class="register-fallback" href="https://wa.me/263776706614" target="_blank" rel="noopener noreferrer">WhatsApp +263 77 670 6614</a><a class="register-fallback" href="https://wa.me/263716949297" target="_blank" rel="noopener noreferrer">WhatsApp +263 71 694 9297</a>'}
function showRegisterResult(heading,body,withFallbacks){registerPending.innerHTML='<b class="status-heading">'+heading+'</b><span class="status-body">'+body+'</span>'+(withFallbacks?'<p class="register-fallbacks">'+contactFallbacks()+'</p>':'');registerPending.hidden=false;try{registerPending.focus()}catch(e){}}
async function submitRegister(){if(registerSending)return;if(!validateRegister())return;registerSending=true;registerSubmitBtn.disabled=true;registerPending.hidden=false;registerPending.setAttribute('aria-busy','true');registerPending.textContent='Submitting your SmartApp interest…';try{if(isLocalPreview()){showRegisterResult('DEVELOPMENT BUILD','Netlify form submission becomes active on an authorised Netlify deployment. Nothing has been submitted from this local preview.',false);return}const body=new URLSearchParams(new FormData(registerForm)).toString();const res=await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!res.ok)throw new Error('netlify http '+res.status);showRegisterResult('INTEREST REGISTERED','Thank you. Your SmartApp interest has been submitted to Tonaque. Our team will review your requirements and contact you using the information provided.',false);registerForm.reset();clearFieldErrors()}catch(err){showRegisterResult('SUBMISSION NOT COMPLETED','We could not submit your information. Your entries have been retained so you can try again. You may also contact Tonaque directly.',true)}finally{registerSending=false;registerSubmitBtn.disabled=false;registerPending.removeAttribute('aria-busy')}}
registerForm.addEventListener('submit',e=>{e.preventDefault();submitRegister()});

